# Generated by Django 5.1.3 on 2024-11-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('address', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('available_tickets', models.PositiveIntegerField(verbose_name='Cantidad de entradas')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.ManyToManyField(to='eventos.category', verbose_name='Categorias')),
            ],
        ),
    ]
