# Generated by Django 5.1.3 on 2024-12-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
