# Generated by Django 5.1.3 on 2024-11-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
